import { defineConfig } from 'tsdown'

export default defineConfig({
    entry: [
        'src/index.ts',
        'src/cli/index.ts',
        'src/api/browser.ts',
        'src/api/server.ts',
        'src/api/config.ts',
        'src/api/noopCss.ts',
        'src/postcss/index.ts',
        'src/eslint-plugin/index.js',
        'src/parser/jsx/browser.ts',
        'src/parser/jsx/server.ts',
        'src/parser/jsx/runtime.ts',
        'src/runtime/index.ts',
        'src/runtime/react.ts',
        'src/runtime/preact.ts',
        'src/runtime/solid.ts',
        'src/runtime/qwik.ts',
        'src/runtime/stencil.ts',
        'src/runtime/style.ts',
        'src/parser/jsx/native.ts',
        'src/parser/classname/server.ts',
        'src/native/browser.ts',
        'src/native/server.ts',
        'src/prop/pseudo/server.ts',
        'src/prop/pseudo/runtime-only.ts',
        'src/prop/at/server.ts',
        'src/prop/at/runtime-only.ts',
        'src/prop/child/server.ts',
        'src/prop/child/runtime-only.ts',
        'src/prop/css/server.ts',
        'src/prop/css/runtime-only.ts',
        'src/prop/bosswind/server.ts',
        'src/prop/bosswind/browser.ts',
        'src/prop/bosswind/runtime-only.ts',
        'src/strategy/inline-first/browser.ts',
        'src/strategy/inline-first/server.ts',
        'src/strategy/inline-first/runtime-only.ts',
        'src/strategy/runtime-only/css.ts',
        'src/strategy/runtime/server.ts',
        'src/strategy/runtime/runtime-only.ts',
        'src/strategy/classname-first/browser.ts',
        'src/strategy/classname-first/server.ts',
        'src/strategy/classname-only/server.ts',
        'src/reset/server.ts',
        'src/fontsource/server.ts',
        'src/compile/runtime.ts',
        'src/merge/index.ts',
        'src/cx/index.ts',
        'src/detect-fw/index.ts',
        'src/use/token/server.ts',
        'src/use/token/browser.ts',
        'src/use/token/runtime-only.ts',
        'src/ai/server.ts',
        'src/ai/skills.ts',
        'src/dev/server.ts',
        'src/dev/client.ts',
        'src/dev/runtime.ts',
        'src/dev/plugin/server.ts',
        'src/dev/plugin/browser.ts',
        'src/strategy/classname-first/runtime-only.ts',
        'src/strategy/classic/runtime-only.ts',
    ],
    format: ['esm', 'cjs'],
    outDir: 'dist',
    unbundle: true,
    fixedExtension: true,
    skipNodeModulesBundle: true,
})
