name: Bug report
description: Report a reproducible problem in boss-css
title: "bug: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug. Please include a minimal reproduction when possible.

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Clear summary of the bug and the observed behavior.
      placeholder: Describe the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: Describe the expected behavior.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Optional. Share a Boss playground URL (preferred), minimal repo, or step-by-step instructions.
      placeholder: https://bosscss.com/playground

  - type: dropdown
    id: strategy
    attributes:
      label: Strategy mode
      description: Which strategy are you using?
      options:
        - inline-first
        - classname-first
        - classname-only
        - runtime-only
        - runtime-hybrid
        - Not sure
    validations:
      required: true

  - type: input
    id: framework
    attributes:
      label: Framework
      description: React, Next.js, Solid, Qwik, Stencil, etc.
      placeholder: Next.js 14

  - type: input
    id: version
    attributes:
      label: boss-css version
      placeholder: 0.0.14
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, package manager, and anything else relevant.
      placeholder: Node 22, macOS 15, npm 10

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues to avoid creating a duplicate.
          required: true
        - label: I included enough information to reproduce the issue.
          required: true
