import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ClientSide from './ClientSide'
import ClientSide2 from './ClientSide2'
import './globals.css'
import '../.bo$$/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

$$.Prepared = $$.$({
    color: 'red',
})

$$.PreparedUppercaseA = $$.$({
    as: 'a',

    boxShadow: '0 0 0 2px currentColor',
    //href: 'https://www.google.com',
    textTransform: 'uppercase',
    width: 300,
    hover: {
        color: 'purple',
    },

    at: {
        'mobile+': { color: 'cyan' },
    },
    before: {
        content: '""',
    },

    //onClick: () => {},
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <$$.a href="1" fontSize="12" accentColor={[1, 2]}>
                    Bo$$ C$$
                </$$.a>

                <$$.img href="2" src="https://via.placeholder.com/150" alt="placeholder" width={300} />
                <$$.main href="2" />
                <$$
                    as="a"
                    href=""
                    className="before:content:'' hover:before:content:'->' background-color:red"
                    hover={{
                        color: 'green',
                    }}
                >
                    Hover
                </$$>
                <$$
                    tabIndex={1}
                    className={'hover:bg-gray-100'}
                    textTransform={() => 'uppercase'}
                    margin={() => [1, 2, 3]}
                    hover={{
                        color: 'yellow',
                        focus: {
                            color: 'blue',
                        },
                    }}
                >
                    Hover+Focus
                </$$>
                <$$
                    kula
                    at={{
                        '@media (max-width: 768px)': {
                            fontStyle: 'italic',
                        },
                    }}
                >
                    At 768 italic
                </$$>

                <div className="display:flex font-size:32 color:red hover:color:yellow">Div with classname</div>
                <$$ className="display:flex font-size:32 color:red hover:color:yellow" fontWeight="bold">
                    $$ with classname and prop
                </$$>

                <$$ color={$$.token.color.white}>Color prop from token proxy</$$>

                <$$ color="white">Color prop from token shorthand</$$>

                <div className="color:white">Color class with token shorthand</div>

                <div className="color:$$.token.color.white">Token string in classname</div>

                <div className="hover:active:font-size:12">Classname, multiple pseudo (hover:active:font-size:12)</div>

                <$$ color="blue" hover={{ color: $$.token.color.white }}>
                    Color prop from token proxy inside hover
                </$$>

                <$$ margin={[20, 0]}>Array prop; margin: [20, 0]</$$>

                <$$ hover={{ padding: [20, 0] }}>Deep array prop; hover:padding [20, 0]</$$>

                <div className={`margin:20_0`}>Array classname; margin:20_0</div>

                <$$.PreparedUppercaseA>PreparedUppercaseA component (hover, at mobile)</$$.PreparedUppercaseA>

                <ClientSide />
                <ClientSide2 />
                {children}
            </body>
        </html>
    )
}
